#pragma once
#include "domain/World.h"
namespace domain {
// Development-only deterministic 1/10/100-building world, generated by real placements.
// All sizes share flat 13x9 terrain and finish with 640 timber / 160 treasury.
// Failure leaves Out unchanged. The caller owns session/save isolation and warmup.
DOMAINCORE_API Result MakeProfilingFixture(const BuildingCatalog&, std::size_t Count, World& Out);
}
