#include "domain/Prototype.h"
#include "domain/Terrain.h"
#include <chrono>
#include <algorithm>
#include <cmath>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace domain;
#define REQUIRE(x) do { if(!(x))throw std::runtime_error(#x); } while(false)
void Geometry(){REQUIRE(TerrainWalkable(0,0));REQUIRE(TerrainWalkable(0,9600));REQUIRE(!TerrainWalkable(0,4000));REQUIRE(!TerrainWalkable(1500,4000));REQUIRE(TerrainWalkable(3200,4000));REQUIRE(TerrainHeight(6400,0)>400);REQUIRE(TerrainMovementFactor(-6400,-6400)<1);}
void Muster(){World w;PrototypeState p;REQUIRE(MakeTerrainPrototype(w,p));REQUIRE(p.terrain_enabled);REQUIRE(Summarize(w).total==6000);REQUIRE(MusterTerrainArmy(w,p));REQUIRE(Summarize(w).away==2320);REQUIRE(w.formations.size()==25);REQUIRE(w.cohorts.at(7).available==0);REQUIRE(ValidateWorld(w));auto before=w;REQUIRE(!MusterTerrainArmy(w,p));REQUIRE(w==before);
 REQUIRE(BeginPrototypeBattle(w,p,100));auto& rested=p.player_units.begin()->second;rested.fatigue=50;
 REQUIRE(AdvancePrototype(w,p,1'000'000));REQUIRE(rested.fatigue<50);
}
void OrderReservations(){World w;PrototypeState p;REQUIRE(MakeTerrainCombatFixture(w,p,1000));std::vector<EntityId> ids;for(const auto&[id,f]:w.formations)ids.push_back(id);REQUIRE(IssueTerrainOrder(w,p,ids,9600,0,0,CrossingRoute::Ford));auto first=p.navigation.player_paths;REQUIRE(IssueTerrainOrder(w,p,ids,9600,0,0,CrossingRoute::Ford));REQUIRE(first==p.navigation.player_paths);
 {auto copy=w;auto state=p;REQUIRE(AdvancePrototype(w,p,5'000'000));for(int i=0;i<100;++i)REQUIRE(AdvancePrototype(copy,state,50'000));REQUIRE(w==copy&&p==state);}for(auto a=first.begin();a!=first.end();++a)for(auto b=std::next(a);b!=first.end();++b)REQUIRE(std::hypot(a->second.destination.x-b->second.destination.x,a->second.destination.y-b->second.destination.y)>=1500);REQUIRE(AdvancePrototype(w,p,500000));
 REQUIRE(IssueTerrainOrder(w,p,ids,11200,0,0,CrossingRoute::Ford));
 for(int step=0;step<100;++step){REQUIRE(AdvancePrototype(w,p,50000));for(const auto&[id,path]:p.navigation.player_paths)if(path.in_transit)REQUIRE(std::hypot(path.transit.x-path.cell.x,path.transit.y-path.cell.y)<=1600.01);}
 auto before=w;auto prior=p;REQUIRE(!IssueTerrainOrder(w,p,ids,0,4000,0));REQUIRE(w==before&&p==prior);
 World q;PrototypeState state;REQUIRE(MakeTerrainCombatFixture(q,state,1000));
 std::vector<EntityId> pair;for(const auto&[id,f]:q.formations){pair.push_back(id);if(pair.size()==2)break;}
 q.formations.at(pair[0]).facing=3.14;q.formations.at(pair[1]).facing=-3.14;
 const auto original_order=q.formations.at(pair[0]).y-q.formations.at(pair[1]).y;
 REQUIRE(IssueTerrainOrder(q,state,pair,-8000,16000,3.141592653589793));
 REQUIRE(original_order*(state.navigation.player_paths.at(pair[0]).destination.y-state.navigation.player_paths.at(pair[1]).destination.y)>0);
 q.formations.at(pair[0]).x=0;q.formations.at(pair[0]).y=0;q.formations.at(pair[0]).moving=false;state.navigation.player_paths.erase(pair[0]);
 REQUIRE(IssueTerrainOrder(q,state,{pair[0]},9600,9600,0,CrossingRoute::Ford));
}
void CrossingStress(){World w;PrototypeState p;REQUIRE(MakeTerrainPrototype(w,p));w.settlements.at(1).resources.equipment=3000;REQUIRE(RecruitPrototype(w,p,3,2000,TroopRole::Polearm));REQUIRE(RecruitPrototype(w,p,3,1000,TroopRole::Polearm));REQUIRE(BeginPrototypeBattle(w,p,100));for(auto&[id,f]:p.enemy.formations){f.x=24000;f.y=24000;}for(auto&t:p.config.troops)t.attack_per_soldier=0;std::vector<EntityId> ids;for(const auto&[id,f]:w.formations)ids.push_back(id);REQUIRE(ids.size()==30);REQUIRE(IssueTerrainOrder(w,p,ids,9600,0,0,CrossingRoute::Bridge));const auto start=std::chrono::steady_clock::now();double clear_seconds=0;for(int i=0;i<3600;++i){REQUIRE(AdvancePrototype(w,p,100000));if(!clear_seconds){bool cleared=true;for(const auto&[id,f]:w.formations)cleared&=f.x>3000;if(cleared)clear_seconds=(i+1)*.1;}}Quantity crossed=0;for(const auto&[id,f]:w.formations){crossed+=f.x>3000;REQUIRE(TerrainWalkable(f.x,f.y));}auto ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();std::cout<<"BRIDGE30 clear_seconds="<<clear_seconds<<" crossed="<<crossed<<" overlap_peak="<<p.navigation.peak_friendly_overlap_pairs<<" stuck="<<p.navigation.stuck_formations<<" waits="<<p.navigation.waiting_formations<<" requests="<<p.navigation.path_requests<<" failed="<<p.navigation.path_failures<<" sim360s_cpu_ms="<<ms<<'\n';REQUIRE(crossed==30);REQUIRE(p.navigation.peak_friendly_overlap_pairs==0);REQUIRE(p.navigation.stuck_formations==0);}
void SecondWar(){World w;PrototypeState p;REQUIRE(MakeTerrainPrototype(w,p));REQUIRE(MusterTerrainArmy(w,p));REQUIRE(BeginPrototypeBattle(w,p));Quantity elite=0;for(auto&[id,f]:w.formations)if(f.role==TroopRole::SamuraiFoot){f.x=4800;f.y=(elite++-1)*1600;}
 for(int i=0;i<180;++i)REQUIRE(AdvancePrototype(w,p,1'000'000));REQUIRE(p.battle.player_elite_dead>0);auto bad=p;bad.player_units.begin()->second.service_states.push_back(ServiceStatus::Dead);auto before=w;REQUIRE(!ReturnFromPrototypeBattle(w,bad,true));REQUIRE(w==before);auto deaths=p.battle.player_dead,elite_deaths=p.battle.player_elite_dead;REQUIRE(ReturnFromPrototypeBattle(w,p,true));REQUIRE(Summarize(w).dead==deaths);REQUIRE(SetSpeed(w,10));REQUIRE(AdvancePrototype(w,p,MicrosecondsPerDay*7/10));REQUIRE(w.cohorts.at(7).available==120-elite_deaths);REQUIRE(MusterTerrainArmy(w,p));Quantity second_elite=0;for(const auto&[id,f]:w.formations)if(!f.demobilized && f.role==TroopRole::SamuraiFoot)second_elite+=f.service_ids.size();REQUIRE(second_elite<120);REQUIRE(Summarize(w).total==6000);REQUIRE(ValidateWorld(w));std::cout<<"SECOND_WAR first_dead="<<deaths<<" elite_dead="<<elite_deaths<<" second_elite="<<second_elite<<" second_away="<<Summarize(w).away<<'\n';}
void OpposingFord(){
 World w;PrototypeState p;REQUIRE(MakeTerrainPrototype(w,p));REQUIRE(RecruitPrototype(w,p,3,1200,TroopRole::Polearm));REQUIRE(BeginPrototypeBattle(w,p,100));
 std::vector<EntityId> eastbound,westbound;int i=0;for(auto&[id,f]:w.formations){const bool east=i<6;const int local=i%6;f.x=(east?-1:1)*(6400+(local/3)*1600);f.y=8000+(local%3)*1600;f.target_x=f.x;f.target_y=f.y;f.moving=false;(east?eastbound:westbound).push_back(id);++i;}
 for(auto&[id,f]:p.enemy.formations){f.x=24000;f.y=24000;}for(auto&t:p.config.troops)t.attack_per_soldier=0;
 REQUIRE(IssueTerrainOrder(w,p,eastbound,12800,9600,0,CrossingRoute::Ford));REQUIRE(IssueTerrainOrder(w,p,westbound,-12800,9600,3.141592653589793,CrossingRoute::Ford));
 REQUIRE(AdvancePrototype(w,p,360'000'000));int east=0,west=0;for(auto id:eastbound)east+=w.formations.at(id).x>3000;for(auto id:westbound)west+=w.formations.at(id).x<-3000;
 std::cout<<"OPPOSING_FORD east="<<east<<" west="<<west<<" overlap_peak="<<p.navigation.peak_friendly_overlap_pairs<<" stuck="<<p.navigation.stuck_formations<<'\n';REQUIRE(east==6&&west==6);REQUIRE(p.navigation.peak_friendly_overlap_pairs==0);REQUIRE(p.navigation.stuck_formations==0);
}
void RoutedExits(){World w;PrototypeState p;REQUIRE(MakeTerrainPrototype(w,p));REQUIRE(RecruitPrototype(w,p,3,400,TroopRole::Polearm));REQUIRE(BeginPrototypeBattle(w,p,100));std::vector<EntityId> routed;int i=0;for(auto&[id,f]:w.formations){if(i<3){f.x=3200+i*1600;f.y=0;p.player_units.at(id).routed=true;routed.push_back(id);}else{f.x=-24000;f.y=-24000;}f.moving=false;++i;}for(auto&[id,f]:p.enemy.formations){f.x=24000;f.y=24000;}for(auto&t:p.config.troops)t.attack_per_soldier=0;REQUIRE(AdvancePrototype(w,p,180'000'000));int settled=0;for(auto id:routed)settled+=!w.formations.at(id).moving&&w.formations.at(id).x<-20000;std::cout<<"ROUTED_EXITS settled="<<settled<<" stuck="<<p.navigation.stuck_formations<<" overlap="<<p.navigation.peak_friendly_overlap_pairs<<'\n';REQUIRE(settled==3);REQUIRE(p.navigation.peak_friendly_overlap_pairs==0);REQUIRE(p.navigation.stuck_formations==0);}
void CommittedRetreat(){World w;PrototypeState p;REQUIRE(MakeTerrainPrototype(w,p));REQUIRE(RecruitPrototype(w,p,3,200,TroopRole::Polearm));REQUIRE(BeginPrototypeBattle(w,p,100));auto first=w.formations.begin();auto second=std::next(first);first->second.x=0;first->second.y=0;second->second.x=-3200;second->second.y=0;for(auto&[id,f]:p.enemy.formations){f.x=24000;f.y=24000;}for(auto&t:p.config.troops)t.attack_per_soldier=0;REQUIRE(IssueTerrainOrder(w,p,{first->first},8000,0,0,CrossingRoute::Bridge));REQUIRE(IssueTerrainOrder(w,p,{second->first},8000,3200,0,CrossingRoute::Bridge));p.player_units.at(first->first).routed=true;first->second.moving=false;REQUIRE(AdvancePrototype(w,p,240'000'000));std::cout<<"COMMITTED_RETREAT routed_x="<<first->second.x<<" following_x="<<second->second.x<<" overlap="<<p.navigation.peak_friendly_overlap_pairs<<'\n';REQUIRE(first->second.x<-3000&&second->second.x>3000);REQUIRE(p.navigation.peak_friendly_overlap_pairs==0);}
void ManualArmySequence(){
 World w;PrototypeState p;REQUIRE(MakeTerrainPrototype(w,p));REQUIRE(MusterTerrainArmy(w,p));REQUIRE(BeginPrototypeBattle(w,p));std::vector<EntityId> all,elite;for(const auto&[id,f]:w.formations){all.push_back(id);if(f.role==TroopRole::SamuraiFoot)elite.push_back(id);}
 REQUIRE(IssueTerrainOrder(w,p,all,8000,0,0,CrossingRoute::Bridge));REQUIRE(IssueTerrainOrder(w,p,elite,8000,9600,0,CrossingRoute::Ford));std::set<EntityId> elite_across;int attack_orders=0,attack_rejected=0;for(int i=0;i<1800;++i){REQUIRE(AdvancePrototype(w,p,200000));for(auto id:elite)if(w.formations.at(id).x>3000)elite_across.insert(id);
  if(i==599&&p.phase==BattlePhase::Fighting)for(const auto&[id,u]:p.player_units)if(u.alive>0&&!u.routed){const auto& f=w.formations.at(id);const Formation* target=nullptr;double best=1e100;for(const auto&[other_id,other]:p.enemy_units)if(other.alive>0&&!other.routed){const auto& candidate=p.enemy.formations.at(other_id);double d=std::hypot(candidate.x-f.x,candidate.y-f.y);if(d<best){best=d;target=&candidate;}}
   if(target&&best>.001){double dx=target->x-f.x,dy=target->y-f.y,standoff=f.role==TroopRole::Bow?5600:0;auto result=IssueTerrainOrder(w,p,{id},target->x-dx/best*standoff,target->y-dy/best*standoff,std::atan2(dy,dx));if(result)++attack_orders;else ++attack_rejected;}
  }
 }
 std::cout<<"MANUAL2320 G_orders="<<attack_orders<<" G_rejected="<<attack_rejected<<" elite_crossed="<<elite_across.size()<<" bridge="<<p.navigation.bridge_completions<<" ford="<<p.navigation.ford_completions<<" wait="<<p.navigation.waiting_formations<<" stuck="<<p.navigation.stuck_formations<<" overlap_peak="<<p.navigation.peak_friendly_overlap_pairs<<" phase="<<BattlePhaseName(p.phase)<<" actual_seconds="<<p.battle.seconds<<'\n';
 REQUIRE(elite_across.size()==3);REQUIRE(p.navigation.peak_friendly_overlap_pairs==0);REQUIRE(ReturnFromPrototypeBattle(w,p,true));REQUIRE(ValidateWorld(w));REQUIRE(Summarize(w).total==6000);
}
std::vector<double> NavSamples;
void NavSample(double ms){NavSamples.push_back(ms);}
void CombatScale(){for(Quantity count:{1000,2000}){World w;PrototypeState p;REQUIRE(MakeTerrainCombatFixture(w,p,count));NavSamples.clear();SetTerrainTimingHook(NavSample);auto start=std::chrono::steady_clock::now();REQUIRE(AdvancePrototype(w,p,180'000'000));SetTerrainTimingHook(nullptr);auto total=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();REQUIRE(!NavSamples.empty());std::sort(NavSamples.begin(),NavSamples.end());std::cout<<"TERRAIN_COMBAT "<<count<<"v"<<count<<" budget180s_actual_seconds="<<p.battle.seconds<<" navsteps="<<NavSamples.size()<<" cpu_ms="<<total<<" navmedian_ms="<<NavSamples[NavSamples.size()/2]<<" navp95_ms="<<NavSamples[NavSamples.size()*95/100]<<" contact="<<p.battle.contact_events<<" ranged="<<p.battle.ranged_attacks<<" bridge="<<p.navigation.bridge_completions<<" ford="<<p.navigation.ford_completions<<" overlap_peak="<<p.navigation.peak_friendly_overlap_pairs<<" dead="<<p.battle.player_dead+p.battle.enemy_dead<<" hill="<<p.navigation.hill_attack_ticks<<" flank="<<p.navigation.flank_attack_ticks<<'\n';REQUIRE(p.battle.contact_events>0 && p.battle.ranged_attacks>0);REQUIRE(p.navigation.bridge_completions>0 && p.navigation.ford_completions>0);REQUIRE(p.navigation.peak_friendly_overlap_pairs==0);REQUIRE(p.navigation.hill_attack_ticks>0 && p.navigation.flank_attack_ticks>0);REQUIRE(ValidateWorld(w));}}
int main(){int failed=0;for(auto[name,test]:std::vector<std::pair<const char*,std::function<void()>>>{{"authored terrain",Geometry},{"real representative muster",Muster},{"reserved deterministic line orders",OrderReservations},{"30 formation bridge traffic",CrossingStress},{"persistent second war and elite depletion",SecondWar},{"actual constrained terrain combat",CombatScale},{"opposing ford traffic",OpposingFord},{"manual 2320 order sequence",ManualArmySequence},{"committed crossing retreat",CommittedRetreat},{"unique routed exits",RoutedExits}}){try{test();std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){++failed;std::cout<<"FAIL "<<name<<": "<<e.what()<<'\n';}}return failed?1:0;}
